plugins {
    id 'java'
    id 'io.github.reyerizo.gradle.jcstress' version '0.8.15'
}

group 'io.github.tech0ver'
version 'DEMO'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()
}

ext {
    junitVersion = '5.12.2'
    jcstressVersion = '0.16'
}

dependencies {
    testImplementation platform("org.junit:junit-bom:${junitVersion}")
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    testImplementation "org.openjdk.jcstress:jcstress-core:${jcstressVersion}"
}

test {
    useJUnitPlatform()
}

jcstress {
    jcstressDependency "org.openjdk.jcstress:jcstress-core:${jcstressVersion}"
}
